resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/0a32ec92c461e144f981864c97546db11b52e46a/snapshot.yaml

packages:
  - .
  - test
  - binary
  - binary/test
  - crypto
  - crypto/test

extra-deps:
  - git: https://github.com/input-output-hk/cardano-prelude
    commit: d3a3dfc451725cc3e17f47677739ba3dc7d9bbee
    subdirs:
      - .
      - test
  - git: https://github.com/well-typed/cborg
    commit: 80fbe0ee5e67a5622e2cb9eaa9d8594a2214322d
    subdirs:
      - cborg


nix:
  shell-file: scripts/nix/stack-shell.nix
