resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/8273fe5f00ac03b0c66ef3841c8e957139ee18f2/snapshot.yaml

packages:
  - cardano-ledger
  - cardano-ledger/test
  - crypto
  - crypto/test

extra-deps:
  - libsystemd-journal-1.4.4

  - tasty-hedgehog-1.0.0.1

  # To be able to use `stack hoogle`
  - haskell-src-exts-1.21.0

  - generic-monoid-0.1.0.0

  - git: https://github.com/input-output-hk/cardano-prelude
    commit: 8273fe5f00ac03b0c66ef3841c8e957139ee18f2
    subdirs:
      - .
      - test

  - git: https://github.com/input-output-hk/cardano-base
    commit: 565df9739781db7589c7220a9125ea46a615dd40
    subdirs:
      - binary
      - binary/test

  - git: https://github.com/input-output-hk/cardano-ledger-specs
    commit: 2f68ce26c684b16dc4fb6f08d3e44cf981d502bb
    subdirs:
      - byron/semantics/executable-spec
      - byron/ledger/executable-spec
      - byron/chain/executable-spec

  # Not yet in Stack
  - bimap-0.4.0

  # Following deps are for cardano-shell
  - git: https://github.com/input-output-hk/cardano-shell
    commit: 455c006e5d1a0c1cf3d31777df24752afcbaab10

  - time-units-1.0.0

  - git: https://github.com/input-output-hk/iohk-monitoring-framework
    commit: bd31cd2f3922010ddb76bb869f29c4e63bb8001b
    subdirs:
      - contra-tracer

  # Extracted from cardano-sl since it's quite useful
  - git: https://github.com/input-output-hk/cardano-sl-x509
    commit: ec96c64c665b741c17b4e38f611315bae9b0b054

  - Unique-0.4.7.6

nix:
  shell-file: nix/stack-shell.nix
