resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/7f8544ae9e162b6664f07093227edb148f1c8a5b/snapshot.yaml

packages:
  - .
  - test
  - specs/ledger/hs
  - specs/semantics/hs

extra-deps:
  - git: https://github.com/input-output-hk/cardano-prelude
    commit: 7161436bd31195b2ddfa7d359cd99f0fe53c881c
    subdirs:
      - .
      - test

  - git: https://github.com/input-output-hk/cardano-chain
    commit: 4d9eec080374179bf15bf9c4fca09cc7d73e5f53
    subdirs:
      - binary
      - binary/test

  - git: https://github.com/input-output-hk/cardano-chain
    commit: 4d9eec080374179bf15bf9c4fca09cc7d73e5f53
    subdirs:
      - crypto
      - crypto/test

  - git: https://github.com/input-output-hk/cardano-mainnet-mirror
    commit: 74ca63f8ad6b47beba2f565c73592cede63ce4b5

  - sequence-0.9.8
  - tasty-hedgehog-0.2.0.0

nix:
  shell-file: scripts/nix/stack-shell.nix
