resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/5eb1f5fff2dda40b2ff398e7e1b73d7bcb6f142d/snapshot.yaml

packages:
  - .
  - test
  - binary
  - binary/test
  - crypto
  - crypto/test

extra-deps:
  - git: https://github.com/input-output-hk/cardano-prelude
    commit: 4365aeb5d5bec9c47083639cc06784e654fefe6d
    subdirs:
      - .
      - test

nix:
  shell-file: scripts/nix/stack-shell.nix
