resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/0a32ec92c461e144f981864c97546db11b52e46a/snapshot.yaml

packages:
  - .
  - test
  - binary
  - binary/test
  - crypto
  - crypto/test

extra-deps:
  - git: https://github.com/input-output-hk/cardano-prelude
    commit: 4365aeb5d5bec9c47083639cc06784e654fefe6d
    subdirs:
      - .
      - test

nix:
  shell-file: scripts/nix/stack-shell.nix
