resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/f2802079ba2c07c4d408e3c0aa000fc363792398/snapshot.yaml

packages:
  - .
  - test
  - binary
  - binary/test
  - crypto
  - crypto/test
  - specs/ledger/hs
  - specs/semantics/hs
  - specs/chain/hs

extra-deps:
  - git: https://github.com/input-output-hk/cardano-prelude
    commit: f2802079ba2c07c4d408e3c0aa000fc363792398
    subdirs:
      - .
      - test
  - sequence-0.9.8

nix:
  shell-file: scripts/nix/stack-shell.nix
