steps:
  - label: 'stack rebuild'
    env:
      AWS_REGION: us-west-1
      S3_BUCKET: appveyor-ci-cache
      CACHE_S3_MAX_SIZE: 2500MB
      STACK_ROOT: "/build/cardano-chain.stack"
    command:
      # cache-s3 needs a build directory that is the same across all buildkite agents.
      # so copy the source into /build/cardano-chain
      - "rm -rf /build/cardano-chain"
      - "cp -R . /build/cardano-chain"
      - "cd /build/cardano-chain"
      - "git lfs install"
      - "git lfs pull"
      - "ls -lh test/resources/epochs/"
      - "nix-build scripts/buildkite -o stack-rebuild"
      - "./stack-rebuild"
    agents:
      system: x86_64-linux
