resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/f2802079ba2c07c4d408e3c0aa000fc363792398/snapshot.yaml

packages:
- chain/hs
- ledger/hs
- semantics/hs

extra-deps:
- hedgehog-0.6.1
- sequence-0.9.8
- tasty-hedgehog-0.2.0.0
- git: https://github.com/input-output-hk/cardano-prelude
  commit: e2d1dfb1ebfd9a8b1a2357bad1bdbdf9d5a7a17b
  subdirs:
    - .
    - test
