resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/5943cb9701516a47de86fa7eb22eb790c613d70a/snapshot.yaml

packages:
  - .
  - test

extra-deps:
  - git: https://github.com/input-output-hk/cardano-prelude
    commit: 339d7384c263a234ff553fe731bed2d7091c9e10
    subdirs:
      - .
      - test

  - ../binary
  - ../binary/test

nix:
  packages:
    - openssl
    - zlib
