resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/4b4457e75303ce352223b9723f7771fac6fe0600/snapshot.yaml

packages:
  - .
  - test

extra-deps:
  - git: https://github.com/input-output-hk/cardano-prelude
    commit: 4365aeb5d5bec9c47083639cc06784e654fefe6d
    subdirs:
      - .
      - test

  - ../binary
  - ../binary/test

nix:
  packages:
    - openssl
    - zlib
